export enum Tags {
  // Semantic tags
  HEADER = 'header',
  FOOTER = 'footer',
  MAIN = 'main',

  // Non-semantic tags
  DIV = 'div',
  BUTTON = 'button',
  INPUT = 'input',
  SPAN = 'span',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  LABEL = 'label',
  SELECT = 'select',
  UL = 'ul',
  LI = 'li',
  TEXTAREA = 'textarea',
  P = 'p',
  A = 'a',
  OPTION = 'option',
  IMG = 'img',
  TABLE = 'table',
  TR = 'tr',
  TD = 'td',
  TH = 'th',
  THEAD = 'thead',
  TBODY = 'tbody',
  DIALOG = 'dialog',
  FORM = 'form',
  SVG = 'svg,',
  CANVAS = 'canvas',
}
